//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiServ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appeal
    {
        public int ID { get; set; }
        public string description { get; set; }
        public Nullable<int> type_problem { get; set; }
        public string status { get; set; }
        public string importance { get; set; }
        public Nullable<int> user { get; set; }
        public string time { get; set; }
        public Nullable<int> applicant { get; set; }
    
        public virtual Applicant Applicant1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
