//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiServ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problem
    {
        public int ID { get; set; }
        public string description { get; set; }
        public string time { get; set; }
        public string device { get; set; }
        public string version { get; set; }
        public Nullable<int> applicant { get; set; }
        public string title_problem { get; set; }
    
        public virtual Applicant Applicant1 { get; set; }
    }
}
