USE [master]
GO

/****** Object:  Database [TaxiServ]    Script Date: 02.03.2022 21:08:14 ******/
DROP DATABASE [TaxiServ]
GO

/****** Object:  Database [TaxiServ]    Script Date: 02.03.2022 21:08:14 ******/
CREATE DATABASE [TaxiServ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TaxiServ', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TaxiServ.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TaxiServ_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TaxiServ_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TaxiServ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TaxiServ] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TaxiServ] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TaxiServ] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TaxiServ] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TaxiServ] SET ARITHABORT OFF 
GO

ALTER DATABASE [TaxiServ] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TaxiServ] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TaxiServ] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TaxiServ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TaxiServ] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TaxiServ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TaxiServ] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TaxiServ] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TaxiServ] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TaxiServ] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TaxiServ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TaxiServ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TaxiServ] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TaxiServ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TaxiServ] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TaxiServ] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TaxiServ] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TaxiServ] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TaxiServ] SET  MULTI_USER 
GO

ALTER DATABASE [TaxiServ] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TaxiServ] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TaxiServ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TaxiServ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TaxiServ] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TaxiServ] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TaxiServ] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TaxiServ] SET  READ_WRITE 
GO

